Repository ITYL-12class-4TEAM/Finmate-Front, pull requests merged in 2025-08, with the labels that each got.

#22 feat: 커뮤니티 페이지(목록, 상세, 등록, 수정) 구현
  src/api/commentLike.js
  src/api/comments.js
  src/api/postLike.js
  src/api/postScrap.js
  src/api/posts.js
  src/components/community/CommentItem.vue
  src/components/community/CustomCheckbox.vue
  src/components/community/PostCard.vue
  src/constants/tags.js
  src/layouts/CommunityLayout.vue
  src/pages/community/CommunityDetail.vue
  src/pages/community/CommunityEdit.vue
  src/pages/community/CommunityLayout.vue
  src/pages/community/CommunityList.vue
  src/pages/community/CommunityWrite.vue
  src/pages/community/communityMock.js
  src/pages/products/ProductsLayout.vue
  src/router/index.js
  src/util/download.js
Labels: enhancement

#30 feat: 전역 토스트 컴포넌트 구현
  src/App.vue
  src/components/common/Modal.vue
  src/components/common/ModalProvider.vue
  src/components/common/Toast.vue
  src/components/common/ToastProvider.vue
  src/composables/useModal.js
  src/composables/useToast.js
Labels: enhancement

#21 Feature/login logout
  src/api/auth.js
  src/api/index.js
  src/api/member.js
  src/api/sms.js
  src/api/validation.js
  src/assets/images/google_icon.png
  src/assets/images/kakao_icon.png
  src/components/layouts/Navbar.vue
  src/main.js
  src/pages/auth/OAuth2Redirect.vue
  src/pages/login/FindIdForm.vue
  src/pages/login/FindPasswordForm.vue
  src/pages/login/LoginForm.vue
  src/pages/login/LoginLayout.vue
  src/pages/login/SignUpForm.vue
  src/router/index.js
  src/stores/useAuthStore.js
Labels: enhancement

#36 fix: login/logout 브랜치 내 API 경로에 누락된 /api prefix 추가
  src/api/auth.js
  src/api/member.js
  src/api/sms.js
  src/api/validation.js
Labels: bug

#32 Feature/my page layout wmti api연동
  src/api/index.js
  src/api/wmti.js
  src/components/mypage/favorite/FavoriteItem.vue
  src/components/mypage/favorite/FavoriteList.vue
  src/components/mypage/favorite/ProductItemMeta.vue
  src/components/mypage/mycomment/CommentPostFilter.vue
  src/components/mypage/portfolio/ProductAddModal.vue
  src/components/mypage/portfolio/first/PortfolioSummaryCard.vue
  src/components/mypage/portfolio/second/AgeComparisonChart.vue
  src/components/mypage/portfolio/tab/PortfolioTabs.vue
  src/components/mypage/recentview/RecentViewList.vue
  src/constants/wmtienums.js
  src/pages/mypage/Account.vue
  src/pages/mypage/AccountDelete.vue
  src/pages/mypage/Favorites.vue
  src/pages/mypage/MyComments.vue
  src/pages/mypage/MypageLayout.vue
  src/pages/mypage/Portfolio.vue
  src/pages/mypage/RecentView.vue
  src/pages/mypage/WMTIHistory.vue
Labels: enhancement

#41 fix: 불필요한 메뉴 주석 처리 및 삭제
  src/components/layouts/DesktopNavbar.vue
  src/components/layouts/MobileMenu.vue
Labels: bug

#40 fix: 마이페이지 최근 상품 업데이트
  src/api/recentView.js
  src/pages/mypage/Favorites.vue
  src/pages/mypage/RecentView.vue
Labels: enhancement

#53 feat: 인증 가드 적용 및 전역 모달 시스템 리팩터링
  src/App.vue
  src/components/common/Modal.vue
  src/components/common/ModalProvider.vue
  src/composables/useModal.js
  src/pages/community/CommunityDetail.vue
  src/pages/community/CommunityEdit.vue
  src/router/index.js
  src/stores/useAuthStore.js
  src/stores/useCommunityStore.js
  src/stores/useMissionStore.js
  src/stores/useModalStore.js
  src/stores/useUserAssetStore.js
  src/stores/useWMTIStore.js
  src/stores/usecCommonStore.js
  src/util/guard.js
Labels: bug, enhancement

#52 Feature/search financial products
  src/api/favorite.js
  src/api/product.js
  src/components/products/ActionButtons.vue
  src/components/products/PreferentialConditions.vue
  src/components/products/ProductDetailHeader.vue
  src/components/products/common/ConfirmationModal.vue
  src/components/products/common/Pagination.vue
  src/components/products/compare/CompareEmptyState.vue
  src/components/products/compare/CompareErrorState.vue
  src/components/products/compare/CompareFloatingBar.vue
  src/components/products/compare/CompareTable.vue
  src/components/products/deposit/BankFilter.vue
  src/components/products/deposit/BankSelectModal.vue
  src/components/products/deposit/DepositProductList.vue
  src/components/products/deposit/DepositSearchForm.vue
  src/components/products/detail/ProductFeatures.vue
  src/components/products/detail/ProductInfoCard.vue
  src/components/products/detail/ProductRateInfo.vue
  src/components/products/savings/SavingsProductList.vue
  src/components/products/savings/SavingsSearchForm.vue
  src/components/products/wishlist/WishlistButton.vue
  src/composables/useCompareList.js
  src/layouts/ProductsLayout.vue
  src/pages/products/ProductCompare.vue
  src/pages/products/ProductDeposit.vue
  src/pages/products/ProductDetail.vue
  src/pages/products/ProductSavings.vue
  src/pages/products/ProductsLayout.vue
  src/router/index.js
Labels: enhancement

#60 Feature/wmti customed porfolio - 프론트 피드백 반영
  src/api/wmti.js
  src/components/wmti/CustomedPortfolio.vue
  src/components/wmti/ThemePortFolio.vue
  src/components/wmti/WMTIQuestion.vue
  src/constants/themePortfolios.js
  src/pages/wmti/BasicSurvey.vue
  src/pages/wmti/PreInfoForm.vue
  src/pages/wmti/SurveyPage.vue
  src/pages/wmti/SurveyResult.vue
  src/pages/wmti/Theme-Collection.vue
  src/pages/wmti/WMTICollection.vue
  src/router/index.js
Labels: enhancement

#71 refactor: 비교 페이지 스타일 변경, gpt 상세 요약을 위한 버튼 추가
  src/components/products/compare/CompareTable.vue
  src/components/products/detail/GptDetailModal.vue
  src/pages/products/ProductCompare.vue
  src/pages/products/ProductDetail.vue
Labels: enhancement

#78 feat: 적금 페이지 생성, 스타일 개선
  src/components/products/ProductDetailHeader.vue
  src/components/products/compare/CompareFloatingBar.vue
  src/components/products/compare/CompareTable.vue
  src/components/products/deposit/BankSelectModal.vue
  src/components/products/deposit/DepositProductList.vue
  src/components/products/deposit/DepositSearchForm.vue
  src/components/products/detail/ProductFeatures.vue
  src/components/products/detail/ProductInfoCard.vue
  src/components/products/detail/ProductRateInfo.vue
  src/components/products/savings/SavingsProductList.vue
  src/components/products/savings/SavingsSearchForm.vue
  src/pages/products/ProductCompare.vue
  src/pages/products/ProductDeposit.vue
  src/pages/products/ProductDetail.vue
  src/pages/products/ProductSavings.vue
Labels: enhancement

#81 Feature/wmti customed porfolio 추가 (사용자 맞춤 포트폴리오)
  src/assets/images/wmti-characters/abmc.png
  src/assets/images/wmti-characters/abml.png
  src/assets/images/wmti-characters/abwc.png
  src/assets/images/wmti-characters/abwl.png
  src/assets/images/wmti-characters/apmc.png
  src/assets/images/wmti-characters/apml.png
  src/assets/images/wmti-characters/apwc.png
  src/assets/images/wmti-characters/apwl.png
  src/assets/images/wmti-characters/ibmc.png
  src/assets/images/wmti-characters/ibml.png
  src/assets/images/wmti-characters/ibwc.png
  src/assets/images/wmti-characters/ibwl.png
  src/assets/images/wmti-characters/ipmc.png
  src/assets/images/wmti-characters/ipml.png
  src/assets/images/wmti-characters/ipwc.png
  src/assets/images/wmti-characters/ipwl.png
  src/components/wmti/CustomedPortfolio.vue
  src/components/wmti/DualBarGraph.vue
  src/components/wmti/RecommendationReason.vue
  src/components/wmti/ResultOverview.vue
  src/components/wmti/ScoreChart.vue
  src/components/wmti/ThemePortFolio.vue
  src/components/wmti/ThemePortFolioToggle.vue
  src/components/wmti/WMTIHeroCard.vue
  src/components/wmti/WMTIQuestion.vue
  src/composables/useAuthError.js
  src/composables/useFormBackup.js
  src/composables/useModalMessages.js
  src/constants/themePortfolios.js
  src/constants/theme_portfolios_full.json
  src/constants/wmtiThemePortfolioMap.js
  src/pages/wmti/BasicSurvey.vue
  src/pages/wmti/PreInfoForm.vue
  src/pages/wmti/SurveyPage.vue
  src/pages/wmti/SurveyResult.vue
  src/pages/wmti/Theme-Collection.vue
  src/router/index.js
Labels: enhancement

#88 Feature/wmti collection - 16종 투자성향 모아보기 페이지 추가
  src/components/layouts/DesktopNavbar.vue
  src/components/layouts/MobileMenu.vue
  src/components/wmti/CustomedPortfolio.vue
  src/components/wmti/WMTIHeroCard.vue
  src/components/wmti/WMTIQuestion.vue
  src/composables/useFormBackup.js
  src/composables/useModalMessages.js
  src/pages/wmti/BasicSurvey.vue
  src/pages/wmti/PreInfoForm.vue
  src/pages/wmti/SurveyPage.vue
  src/pages/wmti/SurveyResult.vue
  src/pages/wmti/WMTICollection.vue
  src/router/index.js
Labels: documentation

#95 Refactor/wmti collection feedback WMTI-Collection 페이지 관련 코드피드백 반영
  src/assets/images/wmti-characters/apml.png
  src/pages/wmti/PreInfoForm.vue
  src/pages/wmti/WMTICollection.vue
Labels: enhancement

#101 Feature/survey result follow up
  public/images/wmti-characters/abmc.png
  public/images/wmti-characters/abml.png
  public/images/wmti-characters/abwc.png
  public/images/wmti-characters/abwl.png
  public/images/wmti-characters/apmc.png
  public/images/wmti-characters/apml.png
  public/images/wmti-characters/apwc.png
  public/images/wmti-characters/apwl.png
  public/images/wmti-characters/ibmc.png
  public/images/wmti-characters/ibml.png
  public/images/wmti-characters/ibwc.png
  public/images/wmti-characters/ibwl.png
  public/images/wmti-characters/ipmc.png
  public/images/wmti-characters/ipml.png
  public/images/wmti-characters/ipwc.png
  public/images/wmti-characters/ipwl.png
  src/components/wmti/CustomedPortfolio.vue
  src/components/wmti/WMTIQuestion.vue
  src/composables/useAuthError.js
  src/pages/wmti/PreInfoForm.vue
  src/pages/wmti/SurveyPage.vue
  src/pages/wmti/SurveyResult.vue
  src/pages/wmti/WMTICollection.vue
  src/router/index.js
  src/stores/useAuthStore.js
Labels: enhancement

#91 Feat : notification
  src/App.vue
  src/api/notification.js
  src/components/layouts/Navbar.vue
  src/components/notification/NotificationButton.vue
  src/components/notification/NotificationDropdown.vue
  src/components/notification/common/NotificationBadge.vue
  src/pages/login/SignUpForm.vue
  src/stores/useAuthStore.js
  src/stores/useNotificationStore.js
Labels: enhancement

#139 Refactor/404 notfound solve 설문결과없을때 '설문결과보기' 시도시, 예외처리 추가 + 투자성향 양방향 그래프 디자인 수정
  src/components/wmti/CustomedPortfolio.vue
  src/components/wmti/ScoreChart.vue
  src/pages/mypage/WMTIHistory.vue
  src/pages/wmti/SurveyResult.vue
Labels: enhancement
